spring:
  profiles:
    include: secret
  application:
    name: reordify
  datasource:
    url: jdbc:postgresql://localhost:5432/spotify_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none   # use Flyway instead of hibernate DDL
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
