spring:
  profiles:
    include: secret
  application:
    name: reordify
  datasource:
    url: jdbc:postgresql://localhost:5432/spotify_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update   # use Flyway instead of hibernate DDL
  flyway:
    enabled: false
    locations: classpath:db/migration
    default-schema: public

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: reordify