spring:
  profiles:
    include: secret
  application:
    name: reordify
  datasource:
    url: jdbc:postgresql://localhost:5432/spotify_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
