spotify:
  client-id: c814ee6de7ae4626b876f7aae4b208ce
  client-secret: 2a4a0bf3c26347d889a909238727b79a
  redirect-uri: http://localhost:8080/api/v1/auth/callback
  scopes:
    - user-read-email
    - user-read-private
    - user-library-modify
    - playlist-read-private
    - playlist-modify-public
    - playlist-modify-private