spotify:
  client-id: c814ee6de7ae4626b876f7aae4b208ce
  client-secret: 832472ad919346dc98ee3a241345af23
  redirect-uri: http://localhost:8080/api/v1/auth/callback
  scopes:
    - user-read-email
    - user-read-private
    - user-library-modify
    - playlist-read-private
    - playlist-modify-public
    - playlist-modify-private