spring:
  profiles:
    include: secret
  application:
    name: reordify

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/spotify_db}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: public

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: reordify