# ————————————————————————
# Global & Alerting Configuration
# ————————————————————————
global:
  scrape_interval: 15s            # how often to scrape targets by default
  evaluation_interval: 15s        # how often to evaluate rules

# Where to find your alerting rules
rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'postgres'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'postgres_exporter:9187' ]

  - job_name: 'spring-app'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'app:8080' ]