version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: ../Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://postgres:5432/spotify_db
      - JDBC_DATABASE_USERNAME=root
      - JDBC_DATABASE_PASSWORD=root
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend_net
      - monitoring_net

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=spotify_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend_net
    ports:
      - "5432:5432"


  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    environment:
      - DATA_SOURCE_NAME=postgresql://root:root@postgres:5432/spotify_db?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    networks:
      - backend_net
      - monitoring_net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../src/main/resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../src/main/resources/prometheus/alerts.yml:/etc/prometheus/alerts.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
      - ../src/main/resources/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - monitoring_net

volumes:
  pgdata:
  grafana-storage:

networks:
  backend_net:
  monitoring_net:
